accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'
urlpatterns = [
    path("password/change/", views.PasswordChangeView.as_view(), name="password_change"),
    path("password/change/done/", views.PasswordChangeDoneView.as_view(), name="password_change_done", ),
    path("password/reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path("password/reset/done/", views.PasswordResetDoneView.as_view(), name="password_reset_done", ),
    path("reset/<uidb64>/<token>/", views.PasswordResetConfirmView.as_view(), name="password_reset_confirm", ),
    path("reset/done/", views.PasswordResetCompleteView.as_view(), name="password_reset_complete", ),
    # path("settings/users/update/<int:pk>", views.UserUpdateWithAdmin.as_view(), name='user_update_admin'),
    # path("settings/users/delete/<int:pk>", views.UserDeleteView.as_view(), name='user_delete'),
    # path("users/update/<int:pk>", views.UserUpdate.as_view(), name='user_update'),
    # path("users/create/", views.UserCreate.as_view(), name='user_create'),
    # path("users/", views.UsersList.as_view(), name='users_list'),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path('login/', views.LoginView.as_view(), name='login'),
    path("", views.DashboardView.as_view(), name="dashboard"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings

urlpatterns = [
    path('main_panel_admin/', admin.site.urls),
    path('accounts/profiles/', include('profiles.urls', namespace='profiles')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('pages.urls', namespace='pages')),
]

urlpatterns = i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    *urlpatterns,
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path
from pages import views

app_name = 'pages'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
]

base/templates/admin_panel/footer.html
{% load i18n %}
<footer>
    <div class="footer-area">
        <p>© Copyright 2018. All right reserved. Template by <a href="https://colorlib.com/wp/">Colorlib</a>.</p>
    </div>
</footer>

base/templates/admin_panel/header_area.html
{% load static %}
{% load i18n %}
<div class="header-area">
    <div class="row align-items-center">
        <!-- nav and search button -->
        <div class="col-md-6 col-sm-8 clearfix">
            <div class="nav-btn pull-left">
                <span></span>
                <span></span>
                <span></span>
            </div>
            <div class="search-box pull-left">
                <form action="#">
                    <input type="text" name="search" placeholder="{% translate 'Search...' %}" required>
                    <i class="ti-search"></i>
                </form>
            </div>
        </div>
        <!-- profile info & task notification -->
        <div class="col-md-6 col-sm-4 clearfix">
            <ul class="notification-area pull-right">
                <a href="{% url 'pages:home' %}"><li><i class="ti-home"></i></li></a>

                <li class="settings-btn">
                    <i class="ti-settings"></i>
                </li>
            </ul>
        </div>
    </div>
</div>

base/templates/admin_panel/index.html
{% load static %}
{% load local_data %}
{% language as pages_language %}
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="{% static 'admin_panel/images/icon/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'admin_panel/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin_panel/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin_panel/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'admin_panel/css/metisMenu.css' %}">
    <link rel="stylesheet" href="{% static 'admin_panel/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin_panel/css/slicknav.min.css' %}">
    <!-- amchart css -->
    <link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all"/>
    <!-- others css -->
    <link rel="stylesheet" href="{% static 'admin_panel/css/typography.css' %}">
    <link rel="stylesheet" href="{% static 'admin_panel/css/default-css.css' %}">
    {% if pages_language == "en" %}
        <link rel="stylesheet" href="{% static 'admin_panel/css/styles.css' %}">
    {% else %}
        <link rel="stylesheet" href="{% static 'admin_panel/css/rtl_styles.css' %}">
    {% endif %}
    <link rel="stylesheet" href="{% static 'admin_panel/css/responsive.css' %}">
    <!-- modernizr css -->
    <script src="{% static 'admin_panel/js/vendor/modernizr-2.8.3.min.js' %}"></script>
</head>

<body>
{% include 'admin_panel/preloader.html' %}
<!-- page container area start -->
<div class="page-container">
    {% include 'admin_panel/sidebar.html' %}
    <div class="main-content">
        {% include 'admin_panel/header_area.html' %}

        {% include 'admin_panel/pages_title_area.html' %}

        <div class="main-content-inner">
            {% block main %}{% endblock %}
        </div>
    </div>


    {% include 'admin_panel/footer.html' %}
</div>
<!-- page container area end -->

{% include 'admin_panel/offset.html' %}

<!-- jquery latest version -->
<script src="{% static 'admin_panel/js/vendor/jquery-2.2.4.min.js' %}"></script>
<!-- bootstrap 4 js -->
<script src="{% static 'admin_panel/js/popper.min.js' %}"></script>
<script src="{% static 'admin_panel/js/bootstrap.min.js' %}"></script>
<script src="{% static 'admin_panel/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'admin_panel/js/metisMenu.min.js' %}"></script>
<script src="{% static 'admin_panel/js/jquery.slimscroll.min.js' %}"></script>
<script src="{% static 'admin_panel/js/jquery.slicknav.min.js' %}"></script>

<!-- start chart js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
<!-- start highcharts js -->
<script src="https://code.highcharts.com/highcharts.js"></script>
<!-- start zingchart js -->
<script src="https://cdn.zingchart.com/zingchart.min.js"></script>
<script>
    zingchart.MODULESDIR = "https://cdn.zingchart.com/modules/";
    ZC.LICENSE = ["569d52cefae586f634c54f86dc99e6a9", "ee6b7db5b51705a13dc2339db3edaf6d"];
</script>
<!-- all line chart activation -->
<script src="{% static 'admin_panel/js/line-chart.js' %}"></script>
<!-- all pie chart -->
<script src="{% static 'admin_panel/js/pie-chart.js' %}"></script>
<!-- others plugins -->
<script src="{% static 'admin_panel/js/plugins.js' %}"></script>
<script src="{% static 'admin_panel/js/scripts.js' %}"></script>
</body>

</html>

base/templates/admin_panel/login.html
{% load static %}
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="{% static 'admin_panel/images/icon/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'admin_panel/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin_panel/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin_panel/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'admin_panel/css/metisMenu.css' %}">
    <link rel="stylesheet" href="{% static 'admin_panel/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin_panel/css/slicknav.min.css' %}">
    <!-- amchart css -->
    <link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all"/>
    <!-- others css -->
    <link rel="stylesheet" href="{% static 'admin_panel/css/typography.css' %}">
    <link rel="stylesheet" href="{% static 'admin_panel/css/default-css.css' %}">
    <link rel="stylesheet" href="{% static 'admin_panel/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'admin_panel/css/responsive.css' %}">
    <!-- modernizr css -->
    <script src="{% static 'admin_panel/js/vendor/modernizr-2.8.3.min.js' %}"></script>
</head>

<body>
{% include 'admin_panel/preloader.html' %}

{% block main %}{% endblock %}

<!-- jquery latest version -->
<script src="{% static 'admin_panel/js/vendor/jquery-2.2.4.min.js' %}"></script>
<!-- bootstrap 4 js -->
<script src="{% static 'admin_panel/js/popper.min.js' %}"></script>
<script src="{% static 'admin_panel/js/bootstrap.min.js' %}"></script>
<script src="{% static 'admin_panel/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'admin_panel/js/metisMenu.min.js' %}"></script>
<script src="{% static 'admin_panel/js/jquery.slimscroll.min.js' %}"></script>
<script src="{% static 'admin_panel/js/jquery.slicknav.min.js' %}"></script>

<!-- others plugins -->
<script src="{% static 'admin_panel/js/plugins.js' %}"></script>
<script src="{% static 'admin_panel/js/scripts.js' %}"></script>
</body>

</html>

base/templates/admin_panel/offset.html
{% load i18n %}
<div class="offset-area">
    <div class="offset-close"><i class="ti-close"></i></div>
    <ul class="nav offset-menu-tab">
        <li><a class="active" data-toggle="tab" href="#activity">Activity</a></li>
        <li><a data-toggle="tab" href="#settings">Settings</a></li>
    </ul>
    <div class="offset-content tab-content">
        <div id="activity" class="tab-pane fade in show active">
            <div class="recent-activity">
                <div class="timeline-task">
                    <div class="icon bg1">
                        <i class="fa fa-envelope"></i>
                    </div>
                    <div class="tm-title">
                        <h4>Rashed sent you an email</h4>
                        <span class="time"><i class="ti-time"></i>09:35</span>
                    </div>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse distinctio itaque at.
                    </p>
                </div>
                <div class="timeline-task">
                    <div class="icon bg2">
                        <i class="fa fa-check"></i>
                    </div>
                    <div class="tm-title">
                        <h4>Added</h4>
                        <span class="time"><i class="ti-time"></i>7 Minutes Ago</span>
                    </div>
                    <p>Lorem ipsum dolor sit amet consectetur.
                    </p>
                </div>
                <div class="timeline-task">
                    <div class="icon bg2">
                        <i class="fa fa-exclamation-triangle"></i>
                    </div>
                    <div class="tm-title">
                        <h4>You missed you Password!</h4>
                        <span class="time"><i class="ti-time"></i>09:20 Am</span>
                    </div>
                </div>
                <div class="timeline-task">
                    <div class="icon bg3">
                        <i class="fa fa-bomb"></i>
                    </div>
                    <div class="tm-title">
                        <h4>Member waiting for you Attention</h4>
                        <span class="time"><i class="ti-time"></i>09:35</span>
                    </div>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse distinctio itaque at.
                    </p>
                </div>
                <div class="timeline-task">
                    <div class="icon bg3">
                        <i class="ti-signal"></i>
                    </div>
                    <div class="tm-title">
                        <h4>You Added Kaji Patha few minutes ago</h4>
                        <span class="time"><i class="ti-time"></i>01 minutes ago</span>
                    </div>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse distinctio itaque at.
                    </p>
                </div>
                <div class="timeline-task">
                    <div class="icon bg1">
                        <i class="fa fa-envelope"></i>
                    </div>
                    <div class="tm-title">
                        <h4>Ratul Hamba sent you an email</h4>
                        <span class="time"><i class="ti-time"></i>09:35</span>
                    </div>
                    <p>Hello sir , where are you, i am egerly waiting for you.
                    </p>
                </div>
                <div class="timeline-task">
                    <div class="icon bg2">
                        <i class="fa fa-exclamation-triangle"></i>
                    </div>
                    <div class="tm-title">
                        <h4>Rashed sent you an email</h4>
                        <span class="time"><i class="ti-time"></i>09:35</span>
                    </div>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse distinctio itaque at.
                    </p>
                </div>
                <div class="timeline-task">
                    <div class="icon bg2">
                        <i class="fa fa-exclamation-triangle"></i>
                    </div>
                    <div class="tm-title">
                        <h4>Rashed sent you an email</h4>
                        <span class="time"><i class="ti-time"></i>09:35</span>
                    </div>
                </div>
                <div class="timeline-task">
                    <div class="icon bg3">
                        <i class="fa fa-bomb"></i>
                    </div>
                    <div class="tm-title">
                        <h4>Rashed sent you an email</h4>
                        <span class="time"><i class="ti-time"></i>09:35</span>
                    </div>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse distinctio itaque at.
                    </p>
                </div>
                <div class="timeline-task">
                    <div class="icon bg3">
                        <i class="ti-signal"></i>
                    </div>
                    <div class="tm-title">
                        <h4>Rashed sent you an email</h4>
                        <span class="time"><i class="ti-time"></i>09:35</span>
                    </div>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse distinctio itaque at.
                    </p>
                </div>
            </div>
        </div>
        <div id="settings" class="tab-pane fade">
            <div class="offset-settings">
                <h4>General Settings</h4>
                <div class="settings-list">
                    <div class="s-settings">
                        <div class="s-sw-title">
                            <h5>Notifications</h5>
                            <div class="s-swtich">
                                <input type="checkbox" id="switch1"/>
                                <label for="switch1">Toggle</label>
                            </div>
                        </div>
                        <p>Keep it 'On' When you want to get all the notification.</p>
                    </div>
                    <div class="s-settings">
                        <div class="s-sw-title">
                            <h5>Show recent activity</h5>
                            <div class="s-swtich">
                                <input type="checkbox" id="switch2"/>
                                <label for="switch2">Toggle</label>
                            </div>
                        </div>
                        <p>The for attribute is necessary to bind our custom checkbox with the input.</p>
                    </div>
                    <div class="s-settings">
                        <div class="s-sw-title">
                            <h5>Show your emails</h5>
                            <div class="s-swtich">
                                <input type="checkbox" id="switch3"/>
                                <label for="switch3">Toggle</label>
                            </div>
                        </div>
                        <p>Show email so that easily find you.</p>
                    </div>
                    <div class="s-settings">
                        <div class="s-sw-title">
                            <h5>Show Task statistics</h5>
                            <div class="s-swtich">
                                <input type="checkbox" id="switch4"/>
                                <label for="switch4">Toggle</label>
                            </div>
                        </div>
                        <p>The for attribute is necessary to bind our custom checkbox with the input.</p>
                    </div>
                    <div class="s-settings">
                        <div class="s-sw-title">
                            <h5>Notifications</h5>
                            <div class="s-swtich">
                                <input type="checkbox" id="switch5"/>
                                <label for="switch5">Toggle</label>
                            </div>
                        </div>
                        <p>Use checkboxes when looking for yes or no answers.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

base/templates/admin_panel/pages_title_area.html
{% load static i18n %}
<div class="page-title-area">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="breadcrumbs-area clearfix">
                <h4 class="page-title pull-left">{% translate 'Dashboard' %}</h4>
                <ul class="breadcrumbs pull-left">
                    <li><a href="index.html">{% translate 'Home' %}</a></li>
                    <li><span>{% translate 'Dashboard' %}</span></li>
                </ul>
            </div>
        </div>
        <div class="col-sm-6 clearfix">
            <div class="user-profile pull-right">
                <img class="avatar user-thumb" src="{% static 'admin_panel/images/author/avatar.png' %}" alt="avatar">
                <h4 class="user-name dropdown-toggle" data-toggle="dropdown">
                    {% firstof user.get_fullname %} <i class="fa fa-angle-down"></i></h4>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">{% translate 'Profile' %}</a>
                    <a class="dropdown-item" href="{% url 'accounts:logout' %}">{% translate 'Logout' %}</a>
                </div>
            </div>
        </div>
    </div>
</div>

base/templates/admin_panel/preloader.html
{% load i18n %}
<p class="browserupgrade"></p>
<!-- preloader area start -->
<div id="preloader">
    <div class="loader">
    </div>
</div>
<!-- preloader area end -->

base/templates/admin_panel/sidebar.html
{% load static i18n %}

<div class="sidebar-menu">
    <div class="sidebar-header">
        <div class="logo">
            <a href="{% url 'accounts:dashboard' %}"><img src="{% static 'admin_panel/images/icon/logo.png' %}" alt="logo"></a>
        </div>
    </div>
    <div class="main-menu">
        <div class="menu-inner">
            <nav>
                <ul class="metismenu" id="menu">
                    <li><a href="{% url 'accounts:dashboard' %}"><i class="ti-dashboard"></i> <span>{% translate 'Dashboard' %}</span></a></li>
                    <li>
                        <a href="javascript:void(0)" aria-expanded="true"><i class="ti-layout-sidebar-left"></i>
                            <span>
                                {% translate 'Account' %}
                            </span>
                        </a>
                        <ul class="collapse">
                            <li><a href="{% url 'accounts:password_change' %}">{% translate 'Change Password' %}</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out"></i> <span>{% translate 'Logout' %}</span></a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>